const fs = require('fs');
const path = require('path');

const trFile = path.join(__dirname, '../public/locales/tr/translation.json');
const trTranslations = JSON.parse(fs.readFileSync(trFile, 'utf8'));

const dictionary = {
  "Add": "Ekle",
  "Search": "Ara",
  "Enable Disable confirmation for items removing": "Öğe silme için onayı etkinleştir / devre dışı bırak",
  "Need Confirm": "Onay Gerekli",
  "Remove selected items": "Seçilen öğeleri kaldır",
  "Remove": "Kaldır",
  "Select all": "Tümünü seç",
  "Next": "İleri",
  "Back": "Geri",
  "Displayed": "Görüntülenen",
  "Selected": "Seçilen",
  "Really delete selected items": "Seçili öğeleri gerçekten silmek istiyor musunuz?",
  "Yes": "Evet",
  "No": "Hayır",
  "Any": "Herhangi",
  "Home": "Ana Sayfa",
  "Open apps": "Açık uygulamalar",
  "Menu": "Menü",
  "App switch": "Uygulama değiştir",
  "Loading HTML content...": "HTML içeriği yükleniyor...",
  "Downloading...": "İndiriliyor...",
  "Download": "İndir",
  "Assets will appear here after launching an application": "Uygulama başlatıldıktan sonra varlıklar burada görünecektir",
  "No assets found": "Varlık bulunamadı",
  "Search assets...": "Varlık ara...",
  "No HTML content available": "HTML içeriği yok",
  "Launching...": "Başlatılıyor...",
  "Running": "Çalışıyor",
  "Terminating...": "Sonlandırılıyor...",
  "Killing...": "Kapatılıyor...",
  "Launch": "Başlat",
  "Terminate": "Sonlandır",
  "Applications will appear here when available": "Uygulamalar hazır olduğunda burada görünecektir",
  "No applications available": "Uygulama yok",
  "Search applications...": "Uygulama ara...",
  "Current rotation:": "Mevcut döndürme:",
  "Portrait": "Dikey",
  "Landscape": "Yatay",
  "Stop Using": "Kullanımı Durdur",
  "Are you sure? Device will be cleaned": "Emin misiniz? Cihaz temizlenecektir",
  "Disconnected": "Bağlantı Kesildi",
  "Offline": "Çevrimdışı",
  "Preparing": "Hazırlanıyor",
  "Busy": "Meşgul",
  "Available": "Uygun",
  "Using": "Kullanımda",
  "Automation": "Otomasyon",
  "Connected": "Bağlı",
  "Unhealthy": "Sağlıksız",
  "Notes": "Notlar",
  "Maintenance": "Bakım",
  "Restart Device": "Cihazı Yeniden Başlat",
  "Are you sure you want to reboot this device?": "Cihazı yeniden başlatmak istediğinizden emin misiniz?",
  "The device will be unavailable for a moment": "Cihaz kısa süreliğine ulaşılamaz olacaktır",
  "Device Port": "Cihaz Portu",
  "Target Host": "Hedef Sunucu",
  "Target Port": "Hedef Port",
  "Port Forwarding": "Port Yönlendirme",
  "Host": "Sunucu",
  "Uninstall": "Kaldır",
  "Package": "Paket",
  "Please, type or select value": "Lütfen değer girin veya seçin",
  "Activity": "Aktivite",
  "Action": "Eylem",
  "Category": "Kategori",
  "Data": "Veri",
  "Hide Manifest": "Manifesti Gizle",
  "Show Manifest": "Manifesti Göster",
  "Launch Activity": "Aktivite Başlat",
  "Clipboard": "Pano",
  "Get clipboard contents": "Pano içeriğini al",
  "Power": "Güç",
  "Restart": "Yeniden Başlat",
  "Unlock device": "Cihazın kilidini aç",
  "Camera": "Kamera",
  "Switch Charset": "Karakter Setini Değiştir",
  "Mute": "Sessize Al",
  "Volume Down": "Sesi Azalt",
  "Volume Up": "Sesi Artır",
  "Set Light Theme": "Açık Temayı Ayarla",
  "Set Dark Theme": "Karanlık Temayı Ayarla",
  "Enable": "Etkinleştir",
  "Disable": "Devre Dışı Bırak",
  "Change language": "Dili değiştir",
  "Small": "Küçük",
  "Normal": "Normal",
  "Big": "Büyük",
  "Rewind": "Geri Sar",
  "Previous": "Önceki",
  "Play/Pause": "Oynat/Duraklat",
  "Stop": "Durdur",
  "Fast Forward": "İleri Sar",
  "Reset all browser settings": "Tüm tarayıcı ayarlarını sıfırla",
  "Open": "Aç",
  "Copy link": "Bağlantıyı kopyala",
  "Run the following on your command line to debug the device from your IDE": "Cihazda IDE'nizden hata ayıklamak için komut satırında aşağıdakini çalıştırın",
  "Executes remote shell commands": "Uzak kabuk komutlarını çalıştırır",
  "Find Device": "Cihaz Bul",
  "Physical Device": "Fiziksel Cihaz",
  "Place": "Yer",
  "Battery": "Pil",
  "Health": "Sağlık",
  "Power Source": "Güç Kaynağı",
  "Status": "Durum",
  "Temperature": "Sıcaklık",
  "Voltage": "Voltaj",
  "Display": "Ekran",
  "Size": "Boyut",
  "Density": "Yoğunluk",
  "Width": "Genişlik",
  "Height": "Yükseklik",
  "Orientation": "Yönlendirme",
  "Encrypted": "Şifrelenmiş",
  "Network": "Ağ",
  "Using Fallback": "Yedek Kullanılıyor",
  "Roaming": "Dolaşım",
  "Type": "Tür",
  "Sub Type": "Alt Tür",
  "Hardware": "Donanım",
  "Manufacturer": "Üretici",
  "Product": "Ürün",
  "Model": "Model",
  "Released": "Çıkış Tarihi",
  "SIM": "SIM",
  "Carrier": "Operatör",
  "Number": "Numara",
  "Memory": "Hafıza",
  "SD Card Mounted": "SD Kart Takılı",
  "Platform": "Platform",
  "OS": "İşletim Sistemi",
  "Version": "Sürüm",
  "Name": "İsim",
  "Cores": "Çekirdek",
  "Frequency": "Frekans",
  "Start": "Başlat",
  "Export": "Dışa Aktar",
  "Waiting for logs": "Günlükler bekleniyor",
  "Click the start button": "Başlat düğmesine tıklayın",
  "Use": "Kullan",
  "Stop Automation": "Otomasyonu Durdur",
  "Mercury Device Farm": "Mercury Cihaz Çiftliği",
  "Realtime control center": "Gerçek zamanlı kontrol merkezi",
  "Browsers": "Tarayıcılar",
  "You are authenticated via an automatic login method": "Otomatik bir giriş yöntemiyle doğrulandınız",
  "Create new user": "Yeni kullanıcı oluştur",
  "Email": "E-posta",
  "Try to reconnect": "Yeniden bağlanmayı dene",
  "Go to Device List": "Cihaz Listesine Git",
  "JSON file": "JSON dosyası",
  "Raw lines": "Ham satırlar",
  "File Name": "Dosya Adı",
  "File Extension": "Dosya Uzantısı",
  "Number of groups": "Grup sayısı",
  "Total duration of groups": "Grupların toplam süresi",
  "Number of repetitions per group": "Grup başına tekrar sayısı",
  "Speed": "Hız",
  "Quality": "Kalite",
  "Location": "Konum",
  "Group Origin": "Grup Kökeni",
  "Really delete this device": "Bu cihazı gerçekten silmek istiyor musunuz?",
  "ADB Port Update Failed": "ADB Port Güncellemesi Başarısız",
  "Update ADB Port": "ADB Portunu Güncelle",
  "ADB Port": "ADB Portu",
  "Storage Id": "Depolama Kimliği",
  "Really update this device": "Bu cihazı gerçekten güncellemek istiyor musunuz?",
  "No value": "Değer yok",
  "Adb port must be in range": "Adb portu aralıkta olmalıdır",
  "Device list": "Cihaz listesi",
  "Set filters for device removing": "Cihaz silme için filtreleri ayarla",
  "Remove Filters": "Filtreleri Kaldır",
  "Device presence state": "Cihaz mevcudiyet durumu",
  "Present": "Mevcut",
  "The device is absent": "Cihaz yok",
  "The device is present": "Cihaz mevcut",
  "Device booking state": "Cihaz rezervasyon durumu",
  "Booked": "Rezerve",
  "The device is not booked": "Cihaz rezerve değil",
  "The device is booked": "Cihaz rezerve edildi",
  "Device notes state": "Cihaz notları durumu",
  "Annotated": "Not Eklenmiş",
  "The device does not have notes": "Cihazın notu yok",
  "The device has notes": "Cihazın notları var",
  "Device controlling state": "Cihaz kontrol durumu",
  "Controlled": "Kontrol ediliyor",
  "The device is not controlled": "Cihaz kontrol edilmiyor",
  "The device is controlled": "Cihaz kontrol ediliyor",
  "In team": "Takımda",
  "Not in team": "Takımda değil",
  "Write an email to the team user selection": "Seçilen takım kullanıcılarına e-posta yaz",
  "Really delete this team": "Bu takımı gerçekten silmek istiyor musunuz?",
  "Team list": "Takım listesi",
  "Group Quota": "Grup Kotası",
  "Grant admin": "Yönetici izni ver",
  "Revoke admin": "Yönetici iznini geri al",
  "Privilege": "Ayrıcalık",
  "Really delete this user": "Bu kullanıcıyı gerçekten silmek istiyor musunuz?",
  "Really grant access to user": "Kullanıcıya gerçekten erişim izni vermek istiyor musunuz?",
  "Really revoke access of this user": "Bu kullanıcının erişimini gerçekten geri almak istiyor musunuz?",
  "User list": "Kullanıcı listesi",
  "Write an email to the user selection": "Seçilen kullanıcılara e-posta yaz",
  "Set filters for user removing": "Kullanıcı silme için filtreleri ayarla",
  "Set groups quota for new users": "Yeni kullanıcılar için grup kotasını ayarla",
  "User group ownership state": "Kullanıcı grup sahipliği durumu",
  "Group Owner": "Grup Sahibi",
  "The user is not a group owner": "Kullanıcı bir grup sahibi değil",
  "The user is a group owner": "Kullanıcı bir grup sahibi",
  "Default groups quota": "Varsayılan grup kotası",
  "Reset": "Sıfırla",
  "Customize": "Özelleştir",
  "Light": "Açık",
  "Dark": "Koyu",
  "System": "Sistem",
  "Username": "Kullanıcı adı",
  "Please enter your login": "Lütfen giriş bilgilerinizi girin",
  "Password": "Şifre",
  "Please enter your password": "Lütfen şifrenizi girin",
  "Log In": "Giriş Yap",
  "Contact Support": "Destek ile İletişime Geç",
  "Device was disconnected": "Cihazın bağlantısı kesildi",
  "Repetitions must exceed 0 for this class": "Bu sınıf için tekrarlar 0'dan büyük olmalıdır",
  "Start date must be before expiration date": "Başlangıç tarihi bitiş tarihinden önce olmalıdır",
  "The difference between expiration date and starting date": "Bitiş tarihi ile başlangıç tarihi arasındaki fark",
  "Unauthorized class while device list is not empty": "Cihaz listesi boş değilken yetkisiz sınıf",
  "Group duration quotas is reached": "Grup süresi kotasına ulaşıldı",
  "Connection failed": "Bağlantı başarısız",
  "Error while getting data": "Veri alınırken hata oluştu",
  "Retry": "Yeniden Dene",
  "Error": "Hata",
  "Stack trace": "Hata İzleme"
};

for (const [key, val] of Object.entries(dictionary)) {
    if (trTranslations[key] === key) {
        trTranslations[key] = val;
    }
}

fs.writeFileSync(trFile, JSON.stringify(trTranslations, null, 2));

console.log('Translated successfully!');
